Host dev-kubernetes-1
  HostName 10.10.8.11
  Port 22
  User vagrant
  StrictHostKeyChecking no

Host dev-kubernetes-2
  HostName 10.10.8.12
  Port 22
  User vagrant
  StrictHostKeyChecking no

Host dev-kubernetes-3
  HostName 10.10.8.13
  Port 22
  User vagrant
  StrictHostKeyChecking no
