# This inventory describe a HA typology with stacked etcd (== same nodes as control plane)
# and 3 worker nodes
# See https://docs.ansible.com/ansible/latest/inventory_guide/intro_inventory.html
# for tips on building your # inventory

# Configure 'ip' variable to bind kubernetes services on a different ip than the default iface
# We should set etcd_member_name for etcd cluster. The node that are not etcd members do not need to set the value,
# or can set the empty string value.
[kube_control_plane]
dev-kubernetes-1 ansible_host=dev-kubernetes-1   ip=10.10.8.11 etcd_member_name=dev-kubernetes-1
dev-kubernetes-2 ansible_host=dev-kubernetes-2   ip=10.10.8.12 etcd_member_name=dev-kubernetes-2
dev-kubernetes-3 ansible_host=dev-kubernetes-3   ip=10.10.8.13 etcd_member_name=dev-kubernetes-3

[etcd:children]
kube_control_plane

[kube_node]
dev-kubernetes-1 ansible_host=dev-kubernetes-1   ip=10.10.8.11
dev-kubernetes-2 ansible_host=dev-kubernetes-2   ip=10.10.8.12
dev-kubernetes-3 ansible_host=dev-kubernetes-3   ip=10.10.8.13

[all:vars]
ansible_user=vagrant
ansible_become=true
ansible_ssh_private_key_file=/root/.ssh/id_vagrant
